name: Rust Tests

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check
      run: cargo check

    - name: Style
      run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    needs: [pre-test]

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
